import test from 'node:test';
import http from 'node:http';
import assert from 'node:assert/strict';
import {createServer,configuration,draftWithProvider} from '../server.mjs';
import {createState,dispatch} from '../shared/core.mjs';
const env={OPENAI_API_KEY:'test-secret-openai',OPENAI_MODEL:'test-model',ANTHROPIC_API_KEY:'test-secret-claude',ANTHROPIC_MODEL:'test-model',GEMINI_API_KEY:'test-secret-gemini',GEMINI_MODEL:'test-model'};
function payload(edition='chatgpt'){const s=dispatch(createState(),{type:'addTask',title:'Reply please',body:'Draft a reply to a fictional request.',source:'Fixture',sensitivity:'shareable'});return {edition,task:s.tasks[0],skill:s.skills.find(s=>s.id==='reply')};}
const result=JSON.stringify({summary:'A fixture',draft:'Test draft.',questions:[]});
const fixture={chatgpt:{status:'completed',output:[{type:'reasoning',summary:[]},{type:'message',content:[{type:'output_text',text:result}]}]},claude:{stop_reason:'end_turn',content:[{type:'thinking',thinking:'do not expose'},{type:'text',text:result}]},gemini:{candidates:[{finishReason:'STOP',content:{parts:[{thought:true,text:'do not expose'},{text:result}]}}]}};
const ok=data=>new Response(JSON.stringify(data),{status:200,headers:{'content-type':'application/json'}});
async function running(t,options={}){const server=createServer({env:{},...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r);}));return {server,base:`http://127.0.0.1:${server.address().port}`};}
test('status exposes configuration but never secrets',()=>{const config=configuration(env);assert.ok(config.chatgpt.configured);assert.ok(!JSON.stringify(config).includes('test-secret'));assert.equal(configuration({}).gemini.configured,false);});
for(const edition of Object.keys(fixture))test(`${edition}: exact draft-only HTTP contract and output parsing`,async()=>{let calls=0;const r=await draftWithProvider(payload(edition),{env,fetchImpl:async(url,opts)=>{calls++;assert.equal(opts.method,'POST');assert.equal(opts.redirect,'error');const body=JSON.parse(opts.body);assert.equal(body.model??'test-model','test-model');assert.ok(!JSON.stringify(body).includes('test-secret'));assert.ok(!Object.hasOwn(body,'tool_choice'));if(edition==='chatgpt'){assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(body.store,false);assert.deepEqual(body.tools,[]);assert.equal(body.max_output_tokens,4096);}if(edition==='claude'){assert.equal(url,'https://api.anthropic.com/v1/messages');assert.equal(opts.headers['anthropic-version'],'2023-06-01');assert.ok(opts.headers.Authorization.startsWith('Bearer '));assert.equal(body.max_tokens,4096);}if(edition==='gemini'){assert.equal(url,'https://generativelanguage.googleapis.com/v1beta/models/test-model:generateContent');assert.equal(opts.headers['x-goog-api-key'],env.GEMINI_API_KEY);assert.equal(body.generationConfig.maxOutputTokens,4096);}return ok(fixture[edition]);}});assert.equal(calls,1);assert.equal(r.result.draft,'Test draft.');assert.ok(!JSON.stringify(r).includes('do not expose'));});
test('no provider calls for missing configuration or private source',async()=>{let calls=0;const fetchImpl=async()=>{calls++;return ok({});};await assert.rejects(draftWithProvider(payload(),{env:{},fetchImpl}),/not configured/);const p=payload();p.task.sensitivity='private';await assert.rejects(draftWithProvider(p,{env,fetchImpl}),/shareable/);assert.equal(calls,0);});
test('rate limits are not retried and raw provider errors are not leaked',async()=>{let calls=0;await assert.rejects(draftWithProvider(payload(),{env,fetchImpl:async()=>{calls++;return new Response('test-secret',{status:429});}}),/rate limit/);assert.equal(calls,1);});
test('incomplete, refused and malformed results cannot become successful drafts',async()=>{for(const [edition,data] of [['chatgpt',{status:'incomplete',output:[]}],['claude',{stop_reason:'max_tokens',content:[]}],['gemini',{candidates:[{finishReason:'SAFETY'}]}]])await assert.rejects(draftWithProvider(payload(edition),{env,fetchImpl:async()=>ok(data)}));await assert.rejects(draftWithProvider(payload(),{env,fetchImpl:async()=>new Response('bad json')}),/invalid/);});
test('network failure cannot expose keys in an error',async()=>{await assert.rejects(draftWithProvider(payload(),{env,fetchImpl:async()=>{throw new Error(env.OPENAI_API_KEY);}}),e=>!e.message.includes('test-secret')&&e.message.includes('reach'));});
test('local static routes serve all editions and never expose .env or server code',async t=>{const {base}=await running(t);for(const path of ['/chatgpt/','/claude/','/gemini/','/shared/core.mjs'])assert.equal((await fetch(base+path)).status,200);for(const path of ['/.env','/server.mjs','/package.json','/%2e%2e/.env','/chatgpt/../.git/config'])assert.equal((await fetch(base+path)).status,404);});
test('cross-origin and hostile Host cannot obtain local API access',async t=>{const {base}=await running(t);assert.equal((await fetch(base+'/api/status',{headers:{Origin:'https://evil.example'}})).status,403);assert.equal(await new Promise((resolve,reject)=>{http.get(base+'/api/status',{headers:{Host:'evil.example'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));}).on('error',reject);}),403);assert.equal((await fetch(base+'/api/status',{headers:{'Sec-Fetch-Site':'cross-site'}})).status,403);});
test('CSRF is mandatory; no credentials are sent to the browser',async t=>{const {base}=await running(t,{env});const status=await (await fetch(base+'/api/status')).json();assert.ok(status.csrf);assert.ok(!JSON.stringify(status).includes('test-secret'));assert.equal((await fetch(base+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())})).status,403);});
test('an explicit valid local API request reaches exactly one provider',async t=>{let calls=0;const {base}=await running(t,{env,fetchImpl:async()=>{calls++;return ok(fixture.chatgpt);}});const {csrf}=await(await fetch(base+'/api/status')).json();const r=await fetch(base+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json','X-Switchboard-CSRF':csrf,Origin:base},body:JSON.stringify(payload())});assert.equal(r.status,200);assert.equal((await r.json()).result.draft,'Test draft.');assert.equal(calls,1);});
test('invalid JSON, type and size fail safely before calling providers',async t=>{const {base}=await running(t);const {csrf}=await(await fetch(base+'/api/status')).json();const headers={'Content-Type':'application/json','X-Switchboard-CSRF':csrf};assert.equal((await fetch(base+'/api/generate',{method:'POST',headers,body:'{'})).status,400);assert.equal((await fetch(base+'/api/generate',{method:'POST',headers:{...headers,'Content-Type':'text/plain'},body:'hello'})).status,415);assert.equal((await fetch(base+'/api/generate',{method:'POST',headers,body:JSON.stringify({big:'x'.repeat(100001)})})).status,413);});
test('requests have a deadline; abort does not assert provider cancellation',async t=>{const {base}=await running(t,{env,deadlineMs:25,fetchImpl:async(url,{signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new Error('aborted'))))});const {csrf}=await(await fetch(base+'/api/status')).json();const r=await fetch(base+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json','X-Switchboard-CSRF':csrf},body:JSON.stringify(payload())});assert.equal(r.status,504);assert.match((await r.json()).error,/may still be billed/);});
